config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  get 'privacy', to: 'homes#privacy'
  get 'terms', to: 'homes#terms'
  resources :users, only: [:new, :create, :show, :edit, :update]
  resources :categories, only: :index do
    resources :items, only: :index
  end
  resources :items, except: :index do
    collection do
      get 'history'
      get 'search'
      get 'category_children', defaults: { format: 'json' }
    end
  end
  resources :posts do
    get 'likes', on: :collection
  end
  resources :likes, only: [:create, :destroy]
  resources :declutterings, only: [:edit, :update, :show]
  resource :recommend, only: :show

  namespace :admin do
    root to: 'users#index'
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    delete 'logout', to: 'user_sessions#destroy'
    resources :posts, only: %i[index edit update show destroy]
    resources :users, only: %i[edit update show destroy]
    resources :items, only: %i[index edit update show destroy] do
      get 'category_children', defaults: { format: 'json' }, on: :collection
    end
  end

  # get 'login', to: 'user_sessions#new'
  # post 'login', to: 'user_sessions#create'
  post 'guest_login', to: 'user_sessions#guest_login'
  delete 'logout', to: 'user_sessions#destroy'

  post "oauth/callback", to: "oauths#callback"
  get "oauth/callback", to: "oauths#callback"
  get "oauth/:provider", to: "oauths#oauth", as: :auth_at_provider

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/shared/_before_login_header.html.erb
<!-- Navbar -->
<div class="navbar bg-neutral border-b">
  <div class="flex-1">
    <%= link_to "steteco", root_path, class: "btn btn-ghost normal-case text-xl" %>
  </div>
  <div class="flex-none md:hidden">
    <%= link_to 'ゲストログイン', guest_login_path, data: { "turbo-method": :post }, class: "btn btn-sm btn-ghost" %>
    <%= link_to 'LINEでログイン', auth_at_provider_path(provider: :line), class: "btn btn-sm btn-ghost" %>
  </div>
</div>

app/views/shared/_bottom_nav.html.erb
<div class="btm-nav bg-neutral lg:hidden">
  <%= link_to categories_path, class: "button", data: { active_class: "active border-primary" } do %>
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" data-slot="icon" class="w-5 h-5 md:w-6 md:h-6">
      <path stroke-linecap="round" stroke-linejoin="round" d="M8.25 6.75h12M8.25 12h12m-12 5.25h12M3.75 6.75h.007v.008H3.75V6.75Zm.375 0a.375.375 0 1 1-.75 0 .375.375 0 0 1 .75 0ZM3.75 12h.007v.008H3.75V12Zm.375 0a.375.375 0 1 1-.75 0 .375.375 0 0 1 .75 0Zm-.375 5.25h.007v.008H3.75v-.008Zm.375 0a.375.375 0 1 1-.75 0 .375.375 0 0 1 .75 0Z" />
    </svg>
    <span class="btm-nav-label text-xs md:text-base">アイテム管理</span>
  <% end %>
  <%= link_to new_item_path, class: "button", data: { active_class: "active border-primary" } do %>
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
      <path stroke-linecap="round" stroke-linejoin="round" d="M12 4.5v15m7.5-7.5h-15" />
    </svg>
    <span class="btm-nav-label text-xs md:text-base">アイテム追加</span>
  <% end %>
  <%= link_to decluttering_path(current_user), class: "button", data: { "turbo" => false, active_class: "active border-primary" } do %>
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5 md:w-6 md:h-6">
      <path stroke-linecap="round" stroke-linejoin="round" d="M3 13.125C3 12.504 3.504 12 4.125 12h2.25c.621 0 1.125.504 1.125 1.125v6.75C7.5 20.496 6.996 21 6.375 21h-2.25A1.125 1.125 0 013 19.875v-6.75zM9.75 8.625c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125v11.25c0 .621-.504 1.125-1.125 1.125h-2.25a1.125 1.125 0 01-1.125-1.125V8.625zM16.5 4.125c0-.621.504-1.125 1.125-1.125h2.25C20.496 3 21 3.504 21 4.125v15.75c0 .621-.504 1.125-1.125 1.125h-2.25a1.125 1.125 0 01-1.125-1.125V4.125z" />
    </svg>
    <span class="btm-nav-label text-xs md:text-base">グラフ</span>
  <% end %>
  <%= link_to history_items_path, class: "button", data: { active_class: "active border-primary" } do %>
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5 md:w-6 md:h-6">
      <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 12h16.5m-16.5 3.75h16.5M3.75 19.5h16.5M5.625 4.5h12.75a1.875 1.875 0 010 3.75H5.625a1.875 1.875 0 010-3.75z" />
    </svg>
    <span class="btm-nav-label text-xs md:text-base">履歴</span>
  <% end %>
  <%= link_to new_post_path, class: "button", data: { active_class: "active border-primary" } do %>
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
      <path stroke-linecap="round" stroke-linejoin="round" d="m16.862 4.487 1.687-1.688a1.875 1.875 0 1 1 2.652 2.652L10.582 16.07a4.5 4.5 0 0 1-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 0 1 1.13-1.897l8.932-8.931Zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0 1 15.75 21H5.25A2.25 2.25 0 0 1 3 18.75V8.25A2.25 2.25 0 0 1 5.25 6H10" />
    </svg>
    <span class="btm-nav-label text-xs md:text-base">投稿</span>
  <% end %>
</div>

app/views/shared/_error_message.html.erb
<% if object.errors.any? %>
  <div class = "border border-rose-600 mx-auto alert alert-error">
    <ul class="list-disc md:ml-5">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <% case message_type %>
  <% when "success" %>
    <div class="animate-flash fixed top-24 translate-x-1/2 right-6 sm:translate-x-0 z-30 w-fit max-w-[90%] sm:max-w-1/2 py-4 px-6 flex justify-center items-center bg-white shadow-lg border border-sky-400 rounded-[3px]">
      <p class="text-base font-bold text-dark-blue-200 !leading-none"><%= message %></p>
    </div>
  <% when "error" %>
    <div class="animate-flash fixed top-24 translate-x-1/2 right-6 sm:translate-x-0 z-30 w-fit max-w-[90%] sm:max-w-1/2 py-4 px-6 flex justify-center items-center bg-white shadow-lg border border-rose-600 rounded-[3px]">
      <p class="text-base font-bold text-secondary-200"><%= message %></p>
    </div>
  <% end %>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer footer-center p-4 bg-neutral text-base-content <%= login_class %>">
  <nav>
    <div class="grid grid-flow-col gap-3">
      <%= link_to "利用規約", terms_path, class: "link link-hover" %>
      <%= link_to "プライバシーポリシー", privacy_path, class: "link link-hover" %>
      <%= link_to "お問い合わせ", privacy_path(anchor: "contact"), class: "link link-hover" %>
    </div>
    <%= link_to "http://www.goo.ne.jp/" do %>
      <% image_tag "//u.xgoo.jp/img/sgoo.png", alt: "supported by goo", title: "supported by goo", class: "w-[100px]" %>
    <% end %>
  </nav>
  <aside>
    <small>© steteco 2023</small>
  </aside>
</footer>

app/views/shared/_header.html.erb
<!-- Navbar -->
<div class="navbar bg-neutral border-b">
  <div class="navbar-start">
    <%= link_to "steteco", root_path, class: "btn btn-ghost normal-case text-xl" %>
  </div>

  <div class="navbar-center hidden lg:block">
    <ul class="menu menu-horizontal px-1">
      <li><%= link_to "アイテム管理", categories_path %></li>
      <li><%= link_to '投稿一覧', posts_path %></li>
      <li><%= link_to 'いいね!一覧', likes_posts_path %></li>
    </ul>
  </div>
  
  <div class="navbar-end">
    <div class="hidden lg:block">
      <%= link_to "アイテム投稿", new_post_path, class: "btn btn-primary" %>
      <%= link_to "アイテム追加", new_item_path, class: "btn btn-primary" %>
    </div>
    <div tabindex="0" class="dropdown dropdown-hover dropdown-end">
      <div class="btn btn-ghost btn-circle avatar">
        <div class="w-10 rounded-full border border-2 bg-base-100">
          <%= image_tag current_user.avatar.url %>
        </div>
      </div>
      <ul tabindex="0" class="dropdown-content z-[1] menu p-2 shadow bg-base-100 rounded-box w-52">
        <% if logged_in? %>
          <li><%= button_to 'ログアウト', logout_path, method: :delete %></li>
          <li><%= link_to 'マイページ', user_path(current_user.id) %></li>
          <li class="hidden lg:block"><%= link_to "グラフ", decluttering_path(current_user), data: { "turbo" => false } %></li>
          <li class="hidden lg:block"><%= link_to "履歴", history_items_path %></li>
          <li class="lg:hidden"><%= link_to '投稿一覧', posts_path %></li>
          <li class="lg:hidden"><%= link_to 'お気に入り一覧', likes_posts_path %></a></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_modal.html.erb
<%= turbo_frame_tag "modal" do %>
  <div data-controller="modal">
    <dialog class="modal" data-modal-target="modal">
      <div class="modal-box">
        <%= yield %>
      </div>
      <form method="dialog" class="modal-backdrop">
        <button>close</button>
      </form>
    </dialog>
  </div>
<% end %>