config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  get 'privacy', to: 'homes#privacy'
  get 'terms', to: 'homes#terms'
  resources :users, only: [:new, :create, :show, :edit, :update]
  resources :categories, only: :index do
    resources :items, only: :index
  end
  resources :items, except: :index do
    collection do
      get 'history'
      get 'search'
      get 'category_children', defaults: { format: 'json' }
    end
  end
  resources :posts do
    get 'likes', on: :collection
  end
  resources :likes, only: [:create, :destroy]
  resources :declutterings, only: [:edit, :update, :show]
  resource :recommend, only: :show

  namespace :admin do
    root to: 'users#index'
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    delete 'logout', to: 'user_sessions#destroy'
    resources :posts, only: %i[index edit update show destroy]
    resources :users, only: %i[edit update show destroy]
    resources :items, only: %i[index edit update show destroy] do
      get 'category_children', defaults: { format: 'json' }, on: :collection
    end
  end

  # get 'login', to: 'user_sessions#new'
  # post 'login', to: 'user_sessions#create'
  post 'guest_login', to: 'user_sessions#guest_login'
  delete 'logout', to: 'user_sessions#destroy'

  post "oauth/callback", to: "oauths#callback"
  get "oauth/callback", to: "oauths#callback"
  get "oauth/:provider", to: "oauths#oauth", as: :auth_at_provider

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/item.rb
class Item < ApplicationRecord
  mount_uploader :image, ImageUploader
  before_save :set_disposed_at

  belongs_to :user
  belongs_to :category

  has_many :posts, dependent: :destroy
  has_one :notification, dependent: :destroy
  accepts_nested_attributes_for :notification, allow_destroy: true

  validates :listing_status, inclusion: [true, false]
  validates :disposal_method, presence: true
  validates :name, presence: true, length: { maximum: 40 }
  validates :price,
            numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 9_999_999,
                            allow_nil: true }

  enum disposal_method: { before: 0, sold: 1, discard: 2 }
  enum color: { nothing: 0, white: 1, black: 2, gray: 3, brown: 4, beige: 5, green: 6, blue: 7, purple: 8, yellow: 9,
                pink: 10, red: 11, orange: 12, gold: 13, silver: 14 }

  scope :before_disposal, -> { where(disposal_method: "before") }
  scope :after_disposal, -> { where.not(disposal_method: "before") }
  scope :upcoming_notification, lambda {
                                  joins(:notification).where('notifications.notify_date > ?', Time.zone.today)
                                                      .order('notifications.notify_date ASC')
                                }
  scope :with_before_disposal, lambda {
                                 includes(:notification).select('items.*, notifications.notify_date')
                                                        .joins(:notification).before_disposal
                               }
  scope :with_after_disposal, -> { select('items.*, notifications.notify_date').joins(:notification).after_disposal }
  scope :search_name, lambda { |view, query|
    items = view == 'history' ? after_disposal : before_disposal
    items.where("name like ?", "%#{query}%")
  }
  scope :random_order, ->(ids) { where(id: ids).order("RANDOM()") }

  def name_with_image
    ActionController::Base.helpers.image_tag(image.url, class: "w-[100px] p-1") + "" + name
  end

  private

  def set_disposed_at
    if disposal_method_changed? && (disposal_method == "sold" || disposal_method == "discard")
      self.disposed_at = Date.current
    elsif disposal_method == "before"
      self.disposed_at = nil
    end
  end
end

app/controllers/admin/items_controller.rb
module Admin
  class ItemsController < Admin::BaseController
    before_action :set_item, only: %i[edit update show destroy]
    before_action :set_categories, only: [:edit, :update]
    before_action :set_child_categories, only: [:edit, :update]

    def index
      @q = Item.ransack(params[:q])
      @items = @q.result(distinct: true).includes(:user).order(id: :asc).page(params[:page])
      @categories_collection = Category.where(ancestry: nil).map do |p|
        [p.title, p.children.map do |c|
                    [c.title, c.id]
                  end]
      end
    end

    def show; end

    def edit
      @parent_category = @item.category.parent_id
    end

    def update
      if @item.update(item_params)
        redirect_to admin_item_path(@item), success: t('defaults.message.updated')
      else
        flash.now[:error] = t('defaults.message.not_updated')
        render :edit, status: :unprocessable_entity
      end
    end

    def category_children
      @category_children = Category.find(params[:parent_id]).children
    end

    def destroy
      @item.destroy!
      redirect_to admin_items_path, success: t('defaults.message.deleted')
    end

    private

    def set_item
      @item = Item.find(params[:id])
    end

    def item_params
      params.require(:item).permit(:name, :price, :image, :image_cache, :listing_status, :disposal_method,
                                   :category_id, :color, notification_attributes: [:notify_date])
    end

    def set_categories
      @categories = Category.where(ancestry: nil)
    end

    def set_child_categories
      @child_categories = @item.category.siblings.order('id ASC')
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:edit, :update, :destroy, :show]
  before_action :set_categories, only: [:new, :create, :edit, :update, :history, :index]
  before_action :set_child_categories, only: [:edit, :update]

  def index
    @category = Category.find(params[:category_id])
    category_ids = @category.subtree_ids
    @q = current_user.items.where(category_id: category_ids).with_before_disposal.ransack(params[:q])
    before_items = @q.result(distinct: true)
    @listed_items = before_items.where(listing_status: true)
    @unlisted_items = before_items.where(listing_status: false)
  end

  def search
    @items = current_user.items.search_name(params[:view], params[:q])
    respond_to do |format|
      format.js
    end
  end

  def show; end

  def new
    @item = Item.new
    @item.build_notification # has_oneのオプション、おそらくhas_oneだからnotification.buildがダメだった
  end

  def edit
    @parent_category = @item.category.parent_id
  end

  def create
    @item = current_user.items.build(item_params)
    if @item.save
      redirect_to categories_path, success: t('.success')
    else
      flash.now[:error] = t('.fail')
      render :new, status: :unprocessable_entity
    end
  end

  def history
    @q = current_user.items.after_disposal.ransack(params[:q])
    @disposal_items = @q.result(distinct: true).page(params[:page])
    @categories_collection = @categories.map { |p| [p.title, p.children.map { |c| [c.title, c.id] }] }
  end

  def category_children
    @category_children = Category.find(params[:parent_id]).children
  end

  def update
    if @item.update(item_params)
      redirect_to item_path(@item), success: t('.success')
    else
      flash.now[:error] = t('.fail')
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @item.destroy!
    redirect_to categories_path, success: t('.success')
  end

  private

  def item_params
    params.require(:item).permit(:name, :price, :image, :image_cache, :listing_status, :disposal_method,
                                 :category_id, :color, notification_attributes: [:notify_date])
  end

  def set_item
    @item = current_user.items.find_by(id: params[:id])
    redirect_to(root_path, error: t('defaults.message.forbidden_access')) unless @item
  end

  def set_categories
    @categories = Category.roots.order(id: :asc)
  end

  def set_child_categories
    @child_categories = @item.category.siblings.order('id ASC')
  end
end

app/views/items/_form.html.erb
<%= render 'shared/error_message', object: f.object %>
  <div class="space-y-2 lg:flex lg:items-center lg:space-x-8">
    <%= f.label :image %>
    <div class="flex justify-center">
      <%= image_tag item.image.url, id: "preview", class: "w-[140px] md:w-[250px]" %>
    </div>
    <div class="text-center">
      <%= f.file_field :image, onchange: "previewFileWithId('preview')", accept: "image/*", class: "file-input file-input-bordered file-input-primary file-input-sm md:file-input-md" %>
      <%= f.hidden_field :image_cache %>
    </div>
  </div>

  <div class="my-6 lg:my-8 lg:flex lg:items-center">
    <%= f.label :name, class: "mb-2 lg:mb-0 lg:mr-5" do %>
      アイテム名<span class="text-xs text-error">*必須</span>
    <% end %>
    <div class="form-control lg:w-3/4">
      <%= f.text_field :name, placeholder: "40文字まで", class: "input input-bordered" %>
    </div>
  </div>

  <%= yield %>

  <%= render "radio_button", f: f %>

  <div class="my-6 lg:my-8 space-y-2 lg:space-y-0 lg:flex lg:items-center">
    <p class="mb-2 lg:mr-8">出品状態<span class="text-xs text-error">*必須</span></p>
    <div class="flex justify-center space-x-2">
      <div class="btn rounded-full px-5">
        <%= f.radio_button :listing_status, true, class: "radio checked:bg-primary" %>
        <%= f.label :listing_status, "出品中", value: true %>
      </div>
  
      <div class="btn rounded-full px-5">
        <%= f.radio_button :listing_status, false, class: "radio checked:bg-primary" %>
        <%= f.label :listing_status, "未出品", value: false %>
      </div>
    </div>
  </div>

  <div class="mb-6 lg:mb-8 space-y-2 lg:space-y-0 lg:flex lg:items-center">
    <p class="mb-2 lg:mr-5">処分方法<span class="text-xs text-error">*必須</span></p>
    <div class="flex justify-center space-x-2">
      <%= f.collection_radio_buttons :disposal_method, Item.disposal_methods_i18n, :first, :last do |b| %>
        <div class="btn rounded-full px-5">
          <%= b.radio_button(class: "radio checked:bg-primary") %>
          <%= b.label %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="lg:flex lg:items-center">
    <%= f.fields_for :notification do |n| %>
      <%= n.label :notify_date, Notification.human_attribute_name(:notify_date) do %>
        通知日<span class="text-xs text-error lg:mr-8">*必須</span>
      <% end %>
      <div class="form-control">
        <%= n.date_field :notify_date, class: "p-2.5" %>
      </div>
    <% end %>
  </div>
  
  <div class="border-b my-6 lg:my-8 lg:flex lg:items-center">
    <%= f.label :price %>
    <div class="form-control lg:w-4/5">
      <%= f.text_field :price, inputmode: "numeric", placeholder: "¥1~9,999,999", class: "input appearance-none bg-transparent border-none focus:outline-none text-right" %>
    </div>
  </div>
  
<div class="flex justify-center">
  <%= f.submit class: "btn btn-primary btn-wide" %>
</div>

app/views/items/_item.html.erb
<div class="py-2 bg-base-100 w-full md:w-3/4 border-b border-slate-300" data-controller="link" data-link-target="toLink" data-action="click->link#toLink" data-href="<%= item_path(item) %>" data-turbo = false>
  <div class="flex items-center w-full justify-between">
    <div class="flex items-center space-x-2">
      <div class="mask mask-squircle p-2 w-24 md:w-28">
        <%= image_tag item.image.url %>
      </div>
      <div>
        <div class="font-bold"><%= truncate(item.name, length: 15) %></div>
        <% if current_page?(history_items_path) %>
          <div class="md:flex md:space-x-5">
            <span class="badge badge-primary"><%= item.listing_status ? '出品中' : '未出品' %></span>
            <span class="badge badge-primary"><%= item.disposal_method_i18n %></span>
            <div>断捨離日: <%= item.disposed_at %></div>
          </div>
        <% else %>
          <div class="md:flex md:space-x-5">
            <% if item.price.present? %>
              <div><%= number_to_currency(item.price, unit: "¥", format: "%u %n") %></div>
            <% end %>
            <div>更新日: <%= item.updated_at.strftime("%Y-%m-%d") %></div>
            <div>通知日: <%= item.notification.notify_date %></div>
          </div>
        <% end %>
      </div>
    </div>
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
      <path stroke-linecap="round" stroke-linejoin="round" d="m8.25 4.5 7.5 7.5-7.5 7.5" />
    </svg>
  </div>
</div>
  

app/views/items/_item_show.html.erb
<tbody>
  <tr>
    <th><%= Category.human_attribute_name(:title) %></th>
    <td><%= item.category.parent.title %> / <%= item.category.title %></td>
  </tr>
  <tr>
    <th><%= Item.human_attribute_name(:color) %></th>
    <td><%= item.color_i18n %></td>
  </tr>
  <tr>
    <th><%= Item.human_attribute_name(:listing_status) %></th>
    <td><%= item.listing_status ? '出品中' : '未出品' %></td>
  </tr>
  <tr>
    <th><%= Item.human_attribute_name(:disposal_method) %></th>
    <td><%= item.disposal_method_i18n %></td>
  </tr>
  <tr>
    <th><%= Notification.human_attribute_name(:notify_date) %></th>
    <td><%= item.notification.notify_date %></td>
  </tr>
  <tr>
    <th><%= Item.human_attribute_name(:price) %></th>
    <td><%= number_to_currency(item.price, unit: "¥", format: "%u %n") %></td>
  </tr>
</tbody>

app/views/items/_radio_button.html.erb
<div class="lg:flex lg:items-center">
  <p class="mb-2 lg:mb-0 lg:mr-5 lg:w-1/4">カラー</p>
  <div class="overflow-x-scroll space-x-2 flex hidden-scrollbar">
    <div class="btn rounded-full">
      <%= f.radio_button :color, :nothing, class: "radio checked:bg-primary" %>
      <%= f.label :color, "なし", value: "nothing" %>
    </div>
    <div class="btn rounded-full">
      <%= f.radio_button :color, :white, class: "radio checked:bg-slate-100" %>
      <%= f.label :color, "ホワイト", value: "white" %>
    </div>
    <div class="btn rounded-full">
      <%= f.radio_button :color, :black, class: "radio checked:bg-black" %>
      <%= f.label :color, "ブラック", value: "black" %>
    </div>
    <div class="btn rounded-full">
      <%= f.radio_button :color, :gray, class: "radio checked:bg-gray-500" %>
      <%= f.label :color, "グレー", value: "gray" %>
    </div>
    <div class="btn rounded-full">
      <%= f.radio_button :color, :brown, class: "radio checked:bg-amber-800" %>
      <%= f.label :color, "ブラウン", value: "brown" %>
    </div>
    <div class="btn rounded-full">
      <%= f.radio_button :color, :beige, class: "radio checked:bg-amber-600" %>
      <%= f.label :color, "ベージュ", value: "beige" %>
    </div>
    <div class="btn rounded-full">
      <%= f.radio_button :color, :green, class: "radio checked:bg-green-500" %>
      <%= f.label :color, "グリーン", value: "green" %>
    </div>
    <div class="btn rounded-full">
      <%= f.radio_button :color, :blue, class: "radio checked:bg-blue-500" %>
      <%= f.label :color, "ブルー", value: "blue" %>
    </div>
    <div class="btn rounded-full">
      <%= f.radio_button :color, :purple, class: "radio checked:bg-purple-500" %>
      <%= f.label :color, "パープル", value: "purple" %>
    </div>
    <div class="btn rounded-full">
      <%= f.radio_button :color, :yellow, class: "radio checked:bg-yellow-400" %>
      <%= f.label :color, "イエロー", value: "yellow" %>
    </div>
    <div class="btn rounded-full">
      <%= f.radio_button :color, :pink, class: "radio checked:bg-pink-500" %>
      <%= f.label :color, "ピンク", value: "pink" %>
    </div>
    <div class="btn rounded-full">
      <%= f.radio_button :color, :red, class: "radio checked:bg-red-500" %>
      <%= f.label :color, "レッド", value: "red" %>
    </div>
    <div class="btn rounded-full">
      <%= f.radio_button :color, :orange, class: "radio checked:bg-orange-500" %>
      <%= f.label :color, "オレンジ", value: "orange" %>
    </div>
    <div class="btn rounded-full">
      <%= f.radio_button :color, :gold, class: "radio checked:bg-yellow-500" %>
      <%= f.label :color, "ゴールド", value: "gold" %>
    </div>
    <div class="btn rounded-full">
      <%= f.radio_button :color, :silver, class: "radio checked:bg-zinc-400" %>
      <%= f.label :color, "シルバー", value: "silver" %>
    </div>
  </div>
</div>

app/views/items/_search_form.html.erb
<div class="lg:my-8 lg:mx-2">
  <div class="p-2 lg:p-5 lg:bg-base-100 lg:border-2 lg:rounded-md" data-controller="autocomplete" data-autocomplete-url-value=<%= set_value %> role="combobox">
    <p class="hidden lg:block text-center font-bold">詳細検索</p>
    <%= search_form_for @q, url: url, data: { turbo_frame: "items_list", controller: "search", action: "input->search#submit" }, class: "space-y-2" do |f| %>
      <div class="flex flex-col items-center lg:my-5">
        <%= f.search_field :name_cont, data: { autocomplete_target: 'input'}, class: "input input-bordered lg:w-[260px]", placeholder: "キーワード検索" %>
        <%= f.hidden_field :name, data: { autocomplete_target: 'hidden' } %>
        <div class="flex justify-center">
          <ul class="list-group bg-white absolute max-w-max lg:text-sm" data-autocomplete-target="results"></ul>
        </div>
      </div>

      <div class="flex justify-center items-center lg:block">
        <p class="text-sm lg:text-base lg:border-b lg:pb-1 lg:my-4">通知日で検索</p>
        <div class="lg:flex lg:flex-col lg:justify-center lg:items-center">
          <%= f.date_field :notification_notify_date_gteq, class: "md:p-2.5 border" %>
            <span>~</span>
          <%= f.date_field :notification_notify_date_lteq_end_of_day, class: "md:p-2.5 border" %>
        </div>
      </div>
    
      <% if current_page?(history_items_path) %>
        <div class="collapse lg:collapse-open">
          <input type="checkbox" class="lg:hidden" /> 
          <div class="collapse-title text-center lg:hidden">
            詳細検索
          </div>
          <div class="space-y-4 collapse-content">
            <p class="border-b pb-1">カテゴリーで検索</p>
            <div class="flex justify-center">
              <%= f.select :category_id_eq, grouped_options_for_select(@categories_collection), { include_blank: 'カテゴリーを選択してください' }, class: "select select-bordered" %>
            </div>
            <p class="border-b pb-1">出品状態で検索</p>
            <div class="flex justify-center items-center space-x-2 lg:space-y-2 lg:space-x-0 lg:block">
              <div class="flex">
                <%= f.radio_button :listing_status_eq, "", class: "radio checked:bg-primary" %>
                <%= f.label :listing_status_eq, "すべて", value: "" %>
              </div>

              <div class="flex">
                <%= f.radio_button :listing_status_eq, true, class: "radio checked:bg-primary" %>
                <%= f.label :listing_status_eq, "出品中", value: true %>
              </div>

              <div class="flex">
                <%= f.radio_button :listing_status_eq, false, class: "radio checked:bg-primary" %>
                <%= f.label :listing_status_eq, "未出品", value: false %>
              </div>
            </div>

            <p class="border-b pb-1">処分方法で検索</p>
            <div class="flex justify-center items-center space-x-2 lg:space-y-2 lg:space-x-0 lg:block">
              <div class="flex">
                <%= f.radio_button :disposal_method_eq, "", class: "radio checked:bg-primary" %>
                <%= f.label :disposal_method_eq, "すべて", value: "" %>
              </div>
              <%= f.collection_radio_buttons :disposal_method_eq, Item.disposal_methods_i18n.except(:before).invert.map { |key, value| [key, Item.disposal_methods[value]] }, :last, :first do |b| %>
                <div class="flex">
                  <%= b.radio_button(class: "radio checked:bg-primary") %>
                  <%= b.label %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/items/history.html.erb
<% content_for(:title, t('.title')) %>
<main class="flex-grow lg:flex">
  <%= render 'search_form', url: history_items_path, set_value: search_items_path(view: 'history') %>
  <%= turbo_frame_tag "items_list", class: "lg:my-8 lg:mx-2 lg:p-2 lg:w-full bg-base-100 lg:rounded-md" do %>
    <div>
      <div role="tablist" class="tabs justify-around border-b-2 border-primary pb-2">
        <%= sort_link(@q, :name, '名前順', default_order: :desc, class: "tab", role: "tab") %>
        <%= sort_link(@q, :updated_at, '新着順', default_order: :desc, class: "tab", role: "tab") %>
        <%= sort_link(@q, :disposed_at, '断捨離日順', default_order: :desc, class: "tab", role: "tab") %>
      </div>
      <h2 class="text-center font-bold my-2">断捨離済みのアイテム</h2>
      <div class="flex flex-wrap items-center justify-center">
        <% if @disposal_items.present? %>
          <%= render partial: 'item', collection: @disposal_items %>
        <% end %>
      </div>
    </div>
    <%= paginate @disposal_items %>
  <% end %>
</main>

app/views/items/index.html.erb
<% content_for(:title, t('.title')) %>

<div class="md:flex md:justify-center">
  <div class="tabs flex flex-nowrap overflow-x-scroll hidden-scrollbar">
    <%= link_to "ALL", categories_path, class: "tab tab-bordered tab-lg" %>
    <%= render partial: "categories/category", collection: @categories %>
  </div>
</div>

<main class="flex-grow lg:flex">
  <%= render 'search_form', url: category_items_path(@category), set_value: search_items_path(view: 'index') %>
  <%= turbo_frame_tag "items_list", class: "lg:w-full lg:my-8 lg:mx-2 lg:p-2 bg-base-100 lg:rounded-md" do %>
    <div role="tablist" class="tabs justify-around border-b-2 border-primary py-2">
      <%= sort_link(@q, :name, '名前順', default_order: :desc, class: "tab", role: "tab") %>
      <%= sort_link(@q, :updated_at, '新着順', default_order: :desc, class: "tab", role: "tab") %>
      <%= sort_link(@q, :created_at, '作成日順', { class: "tab", role: "tab"}) %>
      <%= sort_link(@q, :notification_notify_date, '通知日順', default_order: :desc, class: "tab", role: "tab") %>
    </div>
    <h2 class="text-center font-bold my-2"><%= @category.title %></h2>
    <div data-controller="tab">
      <div class="tabs tabs-boxed bg-base-100">
        <a class="tab w-1/2 tab-active" data-tab-target="status" data-action="click->tab#status">出品中</a> 
        <a class="tab w-1/2 not-active" data-tab-target="status" data-action="click->tab#status">未出品</a> 
      </div>
      <div class="mt-4" data-tab-target="content">
        <div class="flex flex-wrap items-center justify-center">
          <% if @listed_items.present? %>
            <%= render partial: 'item', collection: @listed_items, locals: { category: @category } %>
          <% end %>
        </div>
      </div>
      <div class="hidden mt-4" data-tab-target="content">
        <div class="flex flex-wrap items-center justify-center">
          <% if @unlisted_items.present? %>
            <%= render partial: 'item', collection: @unlisted_items, locals: { category: @category } %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</main>

app/views/items/search.html.erb
<% @items.each do |item| %>
  <li class="w-[200px] lg:w-[260px] flex items-center gap-x-3.5 py-2 px-3 rounded-md text-sm text-gray-800 hover:bg-blue-200 focus:ring-2 focus:ring-blue-500 dark:text-gray-400 dark:hover:bg-blue-200 dark:hover:text-gray-300" role="option" data-autocomplete-value="<%= item.id %>" data-autocomplete-label="<%= item.name %>">
    <%= item.name %>
  </li>
<% end %>

app/views/items/show.html.erb
<% content_for(:title, t('.title')) %>
<main class="m-auto lg:mx-0">
  <p class="font-bold my-5 lg:ml-10">アイテム画像</p>
  <div class="lg:flex lg:justify-center lg:items-center">
    <div class="flex justify-center items-center lg:w-2/5">
      <%= image_tag @item.image.url, class: "w-[180px] md:w-[200px] lg:w-[400px]" %>
    </div>
    <div class="overflow-x-auto lg:p-5 lg:mx-10 lg:bg-base-100 lg:rounded-md lg:w-3/5 lg:border-2">
      <p class="font-bold text-xl my-5"><%= @item.name %></p>
      <p class="font-bold text-lg border-b p-2 text-slate-600">アイテムの詳細</p>
      <table class="table">
        <%= render 'item_show', item: @item %>
      </table>
      <ul class="flex items-center justify-end space-x-2 p-2">
        <li>
          <%= link_to edit_item_path(@item), class: "btn btn-primary" do %>
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
              <path stroke-linecap="round" stroke-linejoin="round" d="m16.862 4.487 1.687-1.688a1.875 1.875 0 1 1 2.652 2.652L6.832 19.82a4.5 4.5 0 0 1-1.897 1.13l-2.685.8.8-2.685a4.5 4.5 0 0 1 1.13-1.897L16.863 4.487Zm0 0L19.5 7.125" />
            </svg>
            <span>編集</span>
          <% end %>
        </li>
        <% if @item.disposal_method_i18n == "処分前" %>
          <li>
            <%= button_to @item, method: :delete, data: { turbo_confirm: "本当に削除しますか？" }, class: "btn btn-error" do %>
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                <path stroke-linecap="round" stroke-linejoin="round" d="m14.74 9-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 0 1-2.244 2.077H8.084a2.25 2.25 0 0 1-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 0 0-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 0 1 3.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 0 0-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 0 0-7.5 0" />
              </svg>
              <span>削除</span>
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to new_post_path(item_id: @item.id), class: "btn btn-neutral" do %>
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                <path stroke-linecap="round" stroke-linejoin="round" d="m16.862 4.487 1.687-1.688a1.875 1.875 0 1 1 2.652 2.652L10.582 16.07a4.5 4.5 0 0 1-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 0 1 1.13-1.897l8.932-8.931Zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0 1 15.75 21H5.25A2.25 2.25 0 0 1 3 18.75V8.25A2.25 2.25 0 0 1 5.25 6H10" />
              </svg>
              <span>投稿<span>
            <% end %>
          </li>
          <li>
            <%= link_to "https://twitter.com/share?url=#{ request.url }&text=【断捨離アイテム】%0a%0a#{ @item.name }%0a%0a【断捨離日】%0a%0a#{ @item.disposed_at }", target: '_blank', class: "btn btn-outline rounded-full btn-primary" do %>
              <%= image_tag "logo-black.png", class: "w-3" %>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</main>