config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  get 'privacy', to: 'homes#privacy'
  get 'terms', to: 'homes#terms'
  resources :users, only: [:new, :create, :show, :edit, :update]
  resources :categories, only: :index do
    resources :items, only: :index
  end
  resources :items, except: :index do
    collection do
      get 'history'
      get 'search'
      get 'category_children', defaults: { format: 'json' }
    end
  end
  resources :posts do
    get 'likes', on: :collection
  end
  resources :likes, only: [:create, :destroy]
  resources :declutterings, only: [:edit, :update, :show]
  resource :recommend, only: :show

  namespace :admin do
    root to: 'users#index'
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    delete 'logout', to: 'user_sessions#destroy'
    resources :posts, only: %i[index edit update show destroy]
    resources :users, only: %i[edit update show destroy]
    resources :items, only: %i[index edit update show destroy] do
      get 'category_children', defaults: { format: 'json' }, on: :collection
    end
  end

  # get 'login', to: 'user_sessions#new'
  # post 'login', to: 'user_sessions#create'
  post 'guest_login', to: 'user_sessions#guest_login'
  delete 'logout', to: 'user_sessions#destroy'

  post "oauth/callback", to: "oauths#callback"
  get "oauth/callback", to: "oauths#callback"
  get "oauth/:provider", to: "oauths#oauth", as: :auth_at_provider

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :post_image, PostImageUploader
  belongs_to :user
  belongs_to :item
  has_many :likes, dependent: :destroy

  validates :content, length: { maximum: 1000 }

  scope :with_item, -> { eager_load([:user, :item]).where.not(items: { disposal_method: "before" }) }
end

app/controllers/admin/posts_controller.rb
module Admin
  class PostsController < Admin::BaseController
    before_action :set_post, only: %i[edit update show destroy]

    def index
      @q = Post.ransack(params[:q])
      @posts = @q.result(distinct: true).includes(:user, :item).order(id: :asc).page(params[:page])
    end

    def show; end
    def edit; end

    def update
      if @post.update(post_params)
        redirect_to admin_post_path(@post), success: t('defaults.message.updated')
      else
        flash.now[:error] = t('defaults.message.not_updated')
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @post.destroy!
      redirect_to admin_posts_path, success: t('defaults.message.deleted')
    end

    private

    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:item_id, :content, :post_image, :post_image_cache)
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_action :require_login, only: [:index, :show]
  before_action :set_post, only: [:edit, :update, :destroy]
  before_action :set_disposal, only: [:new, :create, :edit, :update]
  before_action :set_categories_collection, only: [:index, :likes]

  def index
    @q = Post.preload(:likes).with_item.ransack(params[:q])
    @q.sorts = 'likes_count desc' if @q.sorts.empty?
    @posts = @q.result(distinct: true).page(params[:page])
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
    return if params[:item_id].blank?

    @post.item_id = params[:item_id]
  end

  def edit; end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to posts_path, success: t('.success')
    else
      flash.now[:error] = t('.fail')
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @post.update(post_params)
      redirect_to post_path(@post), success: t('.success')
    else
      flash.now[:error] = t('.fail')
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post.destroy!
    redirect_to posts_path, success: t('.success')
  end

  def likes
    @q = current_user.like_posts.preload(:likes).with_item.ransack(params[:q])
    @like_posts = @q.result(distinct: true).order(likes_count: :desc).page(params[:page])
  end

  private

  def post_params
    params.require(:post).permit(:content, :item_id, :post_image, :post_image_cache)
  end

  def set_post
    @post = current_user.posts.find_by(id: params[:id])
    redirect_to(root_path, error: t('defaults.message.forbidden_access')) unless @post
  end

  def set_disposal
    @disposal_items = current_user.items.includes(:user).after_disposal
  end

  def set_categories_collection
    @categories_collection = Category.roots.map { |p| [p.title, p.children.map { |c| [c.title, c.id] }] }
  end
end

app/views/posts/_form.html.erb
<div data-controller="select">
  <%= form_with model: post, local: true do |f| %>
    <%= render 'shared/error_message', object: f.object %>
    <div class="space-y-5">
      <p class="mb-5 md:mr-8">断捨離済みアイテム<span class="text-xs text-error">*必須</span></p>
      <% if disposal_item.present? %>
        <%= turbo_frame_tag "modal_result" do %>
          <div class="flex justify-center">
            <%= button_tag 'アイテムを選択してください', type: 'button', class: 'select select-bordered items-center md:w-[350px]', onclick: 'modal_select.showModal()', data: { "select-target": "link" } %>
            <%= f.collection_select :item_id, disposal_item, :id, :name, { include_blank: "アイテムを選択してください" }, { class: "hidden", data: { "select-target": "hiddenSelect" } } %>
          </div>
        <% end %>
      <% else %>
          <div class="text-center">断捨離済みのアイテムがありません。</br><span class="text-sm">※履歴ページに表示されているアイテムしか投稿できません。</span></div>
      <% end %>
      <div class="space-y-3 md:flex md:space-x-8 md:items-center">
        <%= f.label :post_image %>
        <div class="flex justify-center">
          <%= image_tag post.post_image.url, id: "preview", class: "w-[180px] md:w-[250px]" %>
        </div>
        <div class="text-center">
          <%= f.file_field :post_image, onchange: "previewFileWithId('preview')", accept: "image/*", class: "file-input file-input-bordered file-input-primary file-input-sm md:file-input-md" %>
          <%= f.hidden_field :post_image_cache %>
        </div>
      </div>
      <div class="md:flex md:items-center">
        <%= f.label :content, class: "md:mr-8" %>
        <div class="form-control md:w-3/4">
          <%= f.text_area :content, placeholder: "1,000文字まで", class: "textarea textarea-bordered mt-3 " %>
        </div>
      </div>
      <div class="flex justify-center">
        <%= f.submit class: "btn btn-primary btn-wide" %>
      </div>
    </div>
  <% end %>

  <dialog id="modal_select" class="modal" data-select-target="modal">
    <div class="modal-box">
      <div class="overflow-y-scroll h-[430px]">
        <%= collection_radio_buttons(:post, :item_id, disposal_item, :id, :name_with_image) do |b| %>
          <div class="hover:bg-base-200 p-1">
            <%= b.radio_button(class: "hidden") %>
            <%= b.label(class: "flex items-center") %>
          </div>
        <% end %>
      </div>
      <div class="flex justify-center">
        <%= button_tag '決定', type: 'button', class: 'btn btn-wide btn-primary', data: { action: "click->select#closeModal", turbo_frame: "modal_result" } %>
      </div>
    </div>
    <form method="dialog" class="modal-backdrop">
      <button>close</button>
    </form>
  </dialog>
</div>

app/views/posts/_like.html.erb
<ul>
  <li class="inline-block">
    <%= button_to likes_path(post_id: post.id), class: "btn btn-sm" do %>
      イイね!
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
        <path stroke-linecap="round" stroke-linejoin="round" d="M21 8.25c0-2.485-2.099-4.5-4.688-4.5-1.935 0-3.597 1.126-4.312 2.733-.715-1.607-2.377-2.733-4.313-2.733C5.1 3.75 3 5.765 3 8.25c0 7.22 9 12 9 12s9-4.78 9-12Z" />
      </svg>
      <%= post.likes.size %>
    <% end %>
  </li>
</ul>

app/views/posts/_like_button.html.erb
<% if logged_in? %>
  <%= turbo_frame_tag dom_id(post, :like_button) do %>
    <% if current_user&.like?(post) %>
      <%= render 'posts/unlike', post: post %>
    <% else %>
      <%= render 'posts/like', post: post %>
    <% end %>
  <% end %>
<% end %>

app/views/posts/_post.html.erb
<div class="card w-[340px] md:w-full lg:w-[650px] m-2">
  <% unless current_page?(user_path(post.user)) %>
    <div class="border-b flex items-center p-3" data-controller="link" data-link-target="toLink" data-action="click->link#toLink" data-href="<%= user_path(post.user) %>" data-turbo = false>
      <div class="avatar mr-2">
        <div class="w-12 rounded-full border border-2">
          <%= image_tag post.user.avatar.url %>
        </div>
      </div>
      <div>
        <p class="font-bold"><%= post.user.name %></p>
      </div> 
    </div>
  <% end %>

  <div class="md:flex md:justify-around">
    <figure class="mt-6 md:mt-0">
      <div class="w-[210px]" data-controller="link" data-link-target="toLink" data-action="click->link#toLink" data-href="<%= post_path(post) %>" data-turbo = false>
        <%= image_tag post.item.image.url %>
      </div>
    </figure>

    <div class="md:flex md:flex-col md:w-3/4">
      <div class="card-body pb-0" data-controller="link" data-link-target="toLink" data-action="click->link#toLink" data-href="<%= post_path(post) %>" data-turbo = false>
        <h2 class="card-title"><%= truncate(post.item.name, length: 15) %></h2>
        <table class="table md:flex-grow">
          <tr>
            <th><%= Category.human_attribute_name(:title) %></th>
            <td><%= post.item.category.parent.title %> / <%= post.item.category.title %></p>
          </tr>
          <tr>
            <th><%= Item.human_attribute_name(:listing_status) %></th>
            <td><%= post.item.listing_status ? '出品中' : '未出品' %></td>
          </tr>
          <tr>
            <th><%= Item.human_attribute_name(:disposal_method) %></th>
            <td><%= post.item.disposal_method_i18n %></td>
          </tr>
        </table>
      </div>

      <div class="flex items-center justify-end h-[50px]">
        <p class="text-sm text-neutral-400 flex mr-2">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
            <path stroke-linecap="round" stroke-linejoin="round" d="M12 6v6h4.5m4.5 0a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
          </svg>
          <%= post.updated_at.strftime("%Y-%m-%d") %>
        </p>
        <% if logged_in? && current_user&.own?(post) %>
          <%= link_to "https://twitter.com/share?url=#{ request.url }&text=【投稿したアイテム】%0a%0a#{ post.item.name }%0a%0a【断捨離日】%0a%0a#{ post.item.disposed_at }", target: '_blank', class: "btn btn-sm", data: { "turbo" => false } do %>
            <%= image_tag "logo-black.png", class: "w-3" %>シェア
          <% end %>
        <% else %>
          <%= render "posts/like_button", post: post %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/_search_form.html.erb
<div class="lg:my-8 lg:mx-2">
  <div class="p-4 lg:bg-base-100 lg:border-2 lg:rounded-md lg:p-5">
    <p class="hidden lg:block lg:text-center lg:font-bold lg:mb-5">詳細検索</p>
    <%= search_form_for @q, url: url, data: { turbo_frame: "posts_list", controller: "search", action: "input->search#submit" } do |f| %>
      <div class="flex justify-center items-center lg:mb-4">
        <%= f.search_field :content_or_item_name_cont, class: "input input-bordered lg:w-[260px]", placeholder: "キーワード検索" %>
      </div>
      
      <div class="collapse lg:collapse-open">
        <input type="checkbox" class="lg:hidden" /> 
        <div class="collapse-title text-center lg:hidden">
          詳細検索
        </div>
        <div class="space-y-4 collapse-content">
          <p class="border-b pb-1">カテゴリーで検索</p>
          <div class="flex justify-center">
            <%= f.select :item_category_id_eq, grouped_options_for_select(@categories_collection), { include_blank: 'カテゴリーを選択してください' }, class: "select select-bordered" %>
          </div>
            
          <p class="border-b pb-1">出品状態で検索</p>
          <div class="flex justify-center items-center space-x-2 lg:space-x-0 lg:space-y-2 lg:block">
            <div class="flex">
              <%= f.radio_button :item_listing_status_eq, "", class: "radio checked:bg-primary" %>
              <%= f.label :item_listing_status_eq, "すべて", value: "" %>
            </div>

            <div class="flex">
              <%= f.radio_button :item_listing_status_eq, true, class: "radio checked:bg-primary" %>
              <%= f.label :item_listing_status_eq, "出品中", value: true %>
            </div>

            <div class="flex">
              <%= f.radio_button :item_listing_status_eq, false, class: "radio checked:bg-primary" %>
              <%= f.label :item_listing_status_eq, "未出品", value: false %>
            </div>
          </div>

          <p class="border-b pb-1">処分方法で検索</p>
          <div class="flex justify-center items-center space-x-2 lg:space-x-0 lg:space-y-2 lg:block">
            <div class="flex">
              <%= f.radio_button :item_disposal_method_eq, "", class: "radio checked:bg-primary" %>
              <%= f.label :item_disposal_method_eq, "すべて", value: "" %>
            </div>
            <%= f.collection_radio_buttons :item_disposal_method_eq, Item.disposal_methods_i18n.except(:before).invert.map { |key, value| [key, Item.disposal_methods[value]] }, :last, :first do |b| %>
              <div class="flex">
                <%= b.radio_button(class: "radio checked:bg-primary") %>
                <%= b.label %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/_unlike.html.erb
<ul>
  <li class="inline-block">
    <%= button_to like_path(current_user.likes.find_by(post_id: post.id)), method: :delete, class: "btn btn-sm" do %>
      イイね!
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-6 h-6">
        <path d="m11.645 20.91-.007-.003-.022-.012a15.247 15.247 0 0 1-.383-.218 25.18 25.18 0 0 1-4.244-3.17C4.688 15.36 2.25 12.174 2.25 8.25 2.25 5.322 4.714 3 7.688 3A5.5 5.5 0 0 1 12 5.052 5.5 5.5 0 0 1 16.313 3c2.973 0 5.437 2.322 5.437 5.25 0 3.925-2.438 7.111-4.739 9.256a25.175 25.175 0 0 1-4.244 3.17 15.247 15.247 0 0 1-.383.219l-.022.012-.007.004-.003.001a.752.752 0 0 1-.704 0l-.003-.001Z" />
      </svg>
      <%= post.likes.size %>
    <% end %>
  </li>
</ul>

app/views/posts/edit.html.erb
<% content_for(:title, t('.title')) %>
<main class="my-auto md:m-auto">
  <div class="p-5">
    <%= render "form", { post: @post, disposal_item: @disposal_items } %>
  </div>
</main>

app/views/posts/index.html.erb
<% content_for(:title, t('.title')) %>
<main class="flex-grow lg:flex">
  <%= render 'search_form', url: posts_path %>
  <%= turbo_frame_tag "posts_list", class: "lg:w-full lg:my-8 lg:mx-2 lg:p-2 bg-base-100 lg:rounded-md" do %>
    <div role="tablist" class="tabs justify-around bg-base-100">
      <%= sort_link(@q, :likes_count, 'いいね順', default_order: :desc, class: "tab", role: "tab") %>
      <%= sort_link(@q, :updated_at, '新着順', default_order: :desc, class: "tab", role: "tab") %>
      <%= sort_link(@q, :created_at, '作成日順', default_order: :asc, class: "tab", role: "tab") %>
    </div>
  
    <div class="flex flex-wrap items-center justify-center px-5 lg:px-0">
      <% if @posts.present? %>
        <%= render @posts %>
      <% else %>
        <p class="text-center">投稿はありません</p>
      <% end %>
    </div>
    <%= paginate @posts %>
  <% end %>
</main>

app/views/posts/likes.html.erb
<% content_for(:title, t('.title')) %>
<main class="flex-grow lg:flex">
  <%= render 'search_form', url: likes_posts_path %>
  <%= turbo_frame_tag "posts_list", class: "lg:w-full lg:my-8 lg:mx-2 lg:p-2 bg-base-100 lg:rounded-md" do %>
    <div class="flex flex-wrap items-center justify-center px-5 lg:px-0">
      <% if @like_posts.present? %>
        <%= render @like_posts %>
      <% else %>
        <p>お気に入りしている投稿はありません</p>
      <% end %>
    </div>
    <%= paginate @like_posts %>
  <% end %>
</main>

app/views/posts/new.html.erb
<% content_for(:title, t('.title')) %>
<main class="my-auto md:m-auto">
  <div class="p-5">
    <%= render "form", { post: @post, disposal_item: @disposal_items } %>
  </div>
</main>

app/views/posts/show.html.erb
<% content_for(:title, t('.title')) %>
<main class="my-auto">
  <% if logged_in? && current_user&.own?(@post) %>
    <div class="flex justify-end items-center px-5 lg:px-10">
      <%= link_to "https://twitter.com/share?url=#{ request.url }&text=#{ @post.item.name }%0a%0a#{ @post.content }", target: '_blank', class: "btn btn-outline rounded-full mr-2 btn-primary" do %>
        <%= image_tag "logo-black.png", class: "w-3" %>
      <% end %>
      <ul>
        <li class="inline-block">
          <%= link_to edit_post_path(@post), class: "btn btn-primary btn-sm md:btn-md" do %>
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
              <path stroke-linecap="round" stroke-linejoin="round" d="m16.862 4.487 1.687-1.688a1.875 1.875 0 1 1 2.652 2.652L6.832 19.82a4.5 4.5 0 0 1-1.897 1.13l-2.685.8.8-2.685a4.5 4.5 0 0 1 1.13-1.897L16.863 4.487Zm0 0L19.5 7.125" />
            </svg>
            <span>編集</span>
          <% end %>
        </li>
        <li class="inline-block">
          <%= button_to @post, method: :delete, data: { turbo_confirm: "本当に削除しますか？" }, class: "btn btn-error btn-sm md:btn-md" do %>
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
              <path stroke-linecap="round" stroke-linejoin="round" d="m14.74 9-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 0 1-2.244 2.077H8.084a2.25 2.25 0 0 1-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 0 0-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 0 1 3.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 0 0-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 0 0-7.5 0" />
            </svg>
            <span>削除</span>
          <% end %>
        </li>
      </ul>
    </div>
  <% else %>
    <div class="flex justify-end items-center px-5 pt-2 lg:px-10">
      <%= render "posts/like_button", post: @post %>
    </div>
  <% end %>
  <div class="px-5 pb-5 lg:px-10 lg:pb-10">
    <div class="p-3 border-b border-secondary flex items-center p-2" data-controller="link" data-link-target="toLink" data-action="click->link#toLink" data-href="<%= user_path(@post.user) %>">
      <div class="avatar mr-2">
        <div class="w-12 rounded-full border border-2 bg-base-100">
          <%= image_tag @post.user.avatar.url %>
        </div>
      </div>
      <div>
        <p class="font-bold"><%= @post.user.name %></p>
      </div> 
    </div>
    <div class="flex justify-end items-center space-x-5 mt-2">
      <p class="text-sm text-neutral-400 flex">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
          <path stroke-linecap="round" stroke-linejoin="round" d="M12 6v6h4.5m4.5 0a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
        </svg>
        <%= @post.updated_at.strftime("%Y-%m-%d") %>
      </p>
    </div>

    <!-- 投稿内容 -->
    <article class="space-y-4">
      <div class="md:flex md:justify-around">
        <p><%= simple_format(h(@post.content), {}, sanitize: false) %></p>
        <% if @post.post_image.present? %>
          <div class="flex justify-center"><%= image_tag @post.post_image.url, class: "w-[150px] md:w-[300px]" %></div>
        <% end %>
      </div>
      <h2 class="p-1 border-b border-secondary flex items-center">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 md:w-8 md:h-8">
          <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 10.5V6a3.75 3.75 0 1 0-7.5 0v4.5m11.356-1.993 1.263 12c.07.665-.45 1.243-1.119 1.243H4.25a1.125 1.125 0 0 1-1.12-1.243l1.264-12A1.125 1.125 0 0 1 5.513 7.5h12.974c.576 0 1.059.435 1.119 1.007ZM8.625 10.5a.375.375 0 1 1-.75 0 .375.375 0 0 1 .75 0Zm7.5 0a.375.375 0 1 1-.75 0 .375.375 0 0 1 .75 0Z" />
        </svg>
        <span class="font-bold ml-2">断捨離したモノ</span>
      </h2>
      <div class="md:flex md:justify-around">
        <% if @post.item.image.present? %>
          <div class="flex justify-center mt-2"><%= image_tag @post.item.image.url, class: "w-[150px] md:w-[300px]" %></div>
        <% end %>
        <table class="table md:w-1/2">
          <tr>
            <th><%= Item.human_attribute_name(:name) %></th>
            <td><%= @post.item.name %></td>
          </tr>
          <tr>
            <th><%= Category.human_attribute_name(:title) %></th>
            <td><%= @post.item.category.parent.title %> / <%= @post.item.category.title %></p>
          </tr>
          <tr>
            <th><%= Item.human_attribute_name(:price) %></th>
            <td><%= number_to_currency(@post.item.price, unit: "¥", format: "%u %n") %></td>
          </tr>
          <tr>
            <th><%= Item.human_attribute_name(:listing_status) %></th>
            <td><%= @post.item.listing_status ? '出品中' : '未出品' %></td>
          </tr>
          <tr>
            <th><%= Item.human_attribute_name(:disposal_method) %></th>
            <td><%= @post.item.disposal_method_i18n %></td>
          </tr>
        </table>
      </div>
    </article>
  </div>
</main>