config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  get 'privacy', to: 'homes#privacy'
  get 'terms', to: 'homes#terms'
  resources :users, only: [:new, :create, :show, :edit, :update]
  resources :categories, only: :index do
    resources :items, only: :index
  end
  resources :items, except: :index do
    collection do
      get 'history'
      get 'search'
      get 'category_children', defaults: { format: 'json' }
    end
  end
  resources :posts do
    get 'likes', on: :collection
  end
  resources :likes, only: [:create, :destroy]
  resources :declutterings, only: [:edit, :update, :show]
  resource :recommend, only: :show

  namespace :admin do
    root to: 'users#index'
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    delete 'logout', to: 'user_sessions#destroy'
    resources :posts, only: %i[index edit update show destroy]
    resources :users, only: %i[edit update show destroy]
    resources :items, only: %i[index edit update show destroy] do
      get 'category_children', defaults: { format: 'json' }, on: :collection
    end
  end

  # get 'login', to: 'user_sessions#new'
  # post 'login', to: 'user_sessions#create'
  post 'guest_login', to: 'user_sessions#guest_login'
  delete 'logout', to: 'user_sessions#destroy'

  post "oauth/callback", to: "oauths#callback"
  get "oauth/callback", to: "oauths#callback"
  get "oauth/:provider", to: "oauths#oauth", as: :auth_at_provider

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  mount_uploader :avatar, AvatarUploader

  has_one :decluttering, dependent: :destroy
  has_many :items, dependent: :destroy
  has_many :notifications, through: :items
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_posts, through: :likes, source: :post
  has_many :authentications, dependent: :destroy
  accepts_nested_attributes_for :authentications

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :email, uniqueness: true, allow_nil: true
  validates :name, presence: true

  enum role: { general: 0, admin: 1, guest: 2 }

  def own?(object)
    id == object.user_id
  end

  def like(post)
    like_posts << post
  end

  def unlike(post)
    like_posts.destroy(post)
  end

  def like?(post)
    like_posts.include?(post)
  end

  def disposal_data_for_past_week
    # 過去１週間の断捨離アイテム数を取得
    items.where(disposed_at: 1.week.ago.to_date..Time.zone.today)
         .where(disposal_method: %w[sold discard])
         .group("DATE(disposed_at)")
         .count
  end

  def disposal_chart_datas
    # 過去1週間の全日についてデータを保証する
    dates = (1.week.ago.to_date..Time.zone.today).map { |date| date.strftime('%Y-%m-%d') }
    counts = dates.map { |date| disposal_data_for_past_week[date.to_date].to_i }
    { dates:, counts: }
  end

  def last_month_disposed_items
    items.where(disposed_at: Time.zone.today.last_month.all_month)
         .where(disposal_method: %w[sold discard])
         .count
  end

  def total_disposed_items
    items.where(disposed_at: Time.zone.today.beginning_of_month..Time.zone.today)
         .where(disposal_method: %w[sold discard])
         .count
  end

  after_create :create_default_decluttering

  private

  def create_default_decluttering
    create_decluttering(goal_amount: 0)
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::BaseController
    before_action :set_user, only: %i[edit update show destroy]

    def index
      @q = User.ransack(params[:q])
      @users = @q.result(distinct: true).order(id: :asc).page(params[:page])
    end

    def show; end
    def edit; end

    def update
      if @user.update(user_params)
        redirect_to admin_user_path(@user), success: t('defaults.message.updated')
      else
        flash.now[:error] = t('defaults.message.not_updated')
        render :edit
      end
    end

    def destroy
      @user.destroy!
      redirect_to admin_root_path, success: t('defaults.message.deleted')
    end

    private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:email, :name, :avatar, :avatar_cache, :role, :introduction)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @user_posts = @user.posts.includes(:item).order(created_at: :desc).page(params[:page]).per(5)
  end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), success: t('.success')
    else
      flash.now[:error] = t('.fail')
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
    return if @user == current_user

    redirect_to current_user, error: t('defaults.message.forbidden_access')
  end

  def user_params
    params.require(:user).permit(:avatar, :avatar_cache, :introduction, :name)
  end
end

app/views/admin/users/_search_form.html.erb
<%= search_form_for @q, url: admin_root_path, data: { turbo_frame: "admin_users_list", controller: "search", action: "input->search#submit" } do |f| %>
  <div class="space-y-2 md:space-y-0 md:flex md:justify-center md:space-x-4">
    <div class='form-control'>
      <%= f.search_field :name_cont, class: "input input-bordered", placeholder: t('defaults.search_word') %>
    </div>
    <div class='form-control'>
      <%= f.select :role_eq, User.roles_i18n.invert.map{|key, value| [key, User.roles[value]]}, { include_blank: t('defaults.unspecified') }, class: "select select-bordered" %>
    </div>
  </div>
<% end %>

app/views/admin/users/_user.html.erb
<tr>
  <td>
    <%= user.id %>
  </td>
  <td>
    <%= user.name %>
  </td>
  <td>
    <%= user.role_i18n %>
  </td>
  <td>
    <%= l user.created_at, format: :long %>
  </td>
  <td class="flex flex-wrap space-y-2 md:space-y-0 md:space-x-2">
    <%= link_to t('defaults.show'), admin_user_path(user), class: 'btn btn-info', data: { "turbo" => false } %>
    <%= link_to t('defaults.edit'), edit_admin_user_path(user), class: 'btn btn-success', data: { "turbo" => false } %>
    <%= button_to t('defaults.delete'), admin_user_path(user), method: :delete, data: { turbo_confirm: t('defaults.message.delete_confirm') }, class: 'btn btn-error whitespace-nowrap' %>
  </td>
</tr>

app/views/admin/users/edit.html.erb
<% content_for(:title, t('.title')) %>
<div class="p-5 space-y-5">
  <h1 class="text-center text-2xl font-bold"><%= t '.title' %></h1>
  <%= form_with model: @user, url: admin_user_path(@user), local: true, class: "space-y-6 p-10 lg:p-16" do |f| %>
    <%= render 'shared/error_message', object: f.object %>
    <div>プロフィール画像</div>
    <div class="flex justify-center">
      <%= f.label :avatar do %>
        <%= image_tag @user.avatar.url, id: "preview", class: "w-24 rounded-full md:w-40" %>
        <%= f.file_field :avatar, onchange: "previewFileWithId(preview)", accept: "image/*", class: "hidden" %>
        <%= f.hidden_field :avatar_cache %>
      <% end %>
    </div>
    <div class="form-control">
      <%= f.label :name, class: "mb-4" %>
      <%= f.text_field :name, class: "input input-bordered" %>
    </div>
    <div class="form-control">
      <%= f.label :introduction, class: "mb-4" %>
      <%= f.text_area :introduction, class: "textarea textarea-bordered" %>
    </div>
    <div class="form-control">
      <%= f.label :role, class: "mb-4" %>
      <%= f.select :role, User.roles_i18n.invert, {}, class: "select select-bordered" %>
    </div>
    <div class="flex justify-center">
      <%= f.submit class: 'btn btn-info px-10' %>
    </div>
  <% end %>
</div>

app/views/admin/users/index.html.erb
<% content_for(:title, t('.title')) %>
<div class="p-5 space-y-8">
  <h1 class="font-bold text-center text-2xl"><%= t('.title') %></h1>
  <div>
    <%= render 'search_form' %>
  </div>
  <%= turbo_frame_tag "admin_users_list" do %>
    <div class="overflow-x-auto">
      <table class="table">
        <thead>
          <tr>
            <th><%= User.human_attribute_name(:id) %></th>
            <th><%= User.human_attribute_name(:name) %></th>
            <th><%= User.human_attribute_name(:role) %></th>
            <th><%= User.human_attribute_name(:created_at) %></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <%= render @users %>
        </tbody>
      </table>
    </div>
    <div>
      <%= paginate @users %>
    </div>
  <% end %>
</div>

app/views/admin/users/show.html.erb
<% content_for(:title, t('.title')) %>
<div class="p-5 space-y-5 md:p-10">
  <h1 class="font-bold text-center text-2xl"><%= t('.title') %></h1> 
  <div class="flex space-x-2 justify-end">
    <%= link_to t('defaults.edit'), edit_admin_user_path(@user), class: 'btn btn-success' %>
    <%= button_to t('defaults.delete'), admin_user_path(@user), method: :delete, data: { turbo_confirm: t('defaults.message.delete_confirm') }, class: 'btn btn-error' %>
  </div>
  <table class="table">
    <tr>
      <th><%= User.human_attribute_name(:id) %></th>
      <td><%= @user.id %></td>
    </tr>
    <tr>
      <th><%= User.human_attribute_name(:role) %></th>
      <td><%= @user.role_i18n %></td>
    </tr>
    <tr>
      <th><%= User.human_attribute_name(:name) %></th>
      <td><%= @user.name %></td>
    </tr>
    <tr>
      <th><%= User.human_attribute_name(:avatar) %></th>
      <td><%= image_tag @user.avatar.url, class: "rounded-full border border-2" %></td>
    </tr>
    <tr>
      <th><%= User.human_attribute_name(:introduction) %></th>
      <td><%= @user.introduction %></td>
    </tr>
    <tr>
      <th><%= User.human_attribute_name(:created_at) %></th>
      <td><%= l @user.created_at, format: :long %></td>
    </tr>
  </table>
</div>